/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package front;

import back.Arbol;
import back.NodoArbol;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author cocol
 */
public class EndGame extends javax.swing.JPanel {

    /**
     * Creates new form EndGame
     */
    Arbol datos = new Arbol();
    NodoArbol activo = new NodoArbol();
   
    
    public EndGame(Arbol datos, NodoArbol activo){
        initComponents();
        this.datos = datos;
        this.activo = activo;
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPersonaje = new javax.swing.JTextField();
        btnAgregarImagen = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(6, 118, 243));
        setPreferredSize(new java.awt.Dimension(860, 460));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(11, 18, 98));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Descripcion del personaje:");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 120, 500, 50);

        txtDescripcion.setBackground(new java.awt.Color(91, 191, 255));
        txtDescripcion.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jPanel1.add(txtDescripcion);
        txtDescripcion.setBounds(10, 170, 500, 50);

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 250, 310, 50);

        txtPersonaje.setBackground(new java.awt.Color(91, 191, 255));
        txtPersonaje.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jPanel1.add(txtPersonaje);
        txtPersonaje.setBounds(10, 60, 500, 50);

        btnAgregarImagen.setBackground(new java.awt.Color(91, 191, 255));
        btnAgregarImagen.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        btnAgregarImagen.setText("Añadir Imagen");
        btnAgregarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarImagenActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarImagen);
        btnAgregarImagen.setBounds(10, 250, 170, 50);

        btnAceptar.setBackground(new java.awt.Color(91, 191, 255));
        btnAceptar.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar);
        btnAceptar.setBounds(210, 380, 110, 40);

        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("En quien estabas pensando?");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(8, 5, 500, 50);

        add(jPanel1);
        jPanel1.setBounds(340, 10, 520, 440);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/genio.jpg"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(0, 80, 350, 300);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        if(txtDescripcion.getText().isBlank() ||txtPersonaje.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "No puede haber ningun dato vacio");
        }else{
            datos.insertarNuevoPersonaje(txtDescripcion.getText(), txtPersonaje.getText(), activo);
        }
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnAgregarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarImagenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregarImagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtPersonaje;
    // End of variables declaration//GEN-END:variables
}
