/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package front;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import back.Arbol;
import back.NodoArbol;

/**
 *
 * @author cocol
 */
public class InGame extends javax.swing.JPanel {

    /**
     * Creates new form InGame
     */
    Arbol datos = new Arbol();
    NodoArbol activo = datos.getRaiz();
    public InGame() {
        initComponents();
        
        SetImageLabel(ImgAki,"/imagenes/genio.jpg");
        cambiarTexto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSi = new javax.swing.JButton();
        btnNo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ImgAki = new javax.swing.JLabel();
        lblPregunta = new javax.swing.JLabel();

        setBackground(new java.awt.Color(6, 118, 243));
        setLayout(null);

        btnSi.setBackground(new java.awt.Color(91, 191, 255));
        btnSi.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        btnSi.setText("Si");
        btnSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiActionPerformed(evt);
            }
        });
        add(btnSi);
        btnSi.setBounds(440, 250, 110, 40);

        btnNo.setBackground(new java.awt.Color(91, 191, 255));
        btnNo.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        btnNo.setText("No");
        btnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoActionPerformed(evt);
            }
        });
        add(btnNo);
        btnNo.setBounds(650, 250, 110, 40);

        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tu personaje ");
        add(jLabel3);
        jLabel3.setBounds(350, 110, 500, 50);

        ImgAki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/genio.jpg"))); // NOI18N
        add(ImgAki);
        ImgAki.setBounds(0, 60, 340, 330);
        add(lblPregunta);
        lblPregunta.setBounds(440, 180, 0, 0);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiActionPerformed
        // TODO add your handling code here:
        if(activo.getHijoDerecho().getHijoIzquierdo()==null && activo.getHijoDerecho().getHijoDerecho()==null){
            //mandar a la ventana de adivinado el personaje
        }else{
            activo = activo.avanzarDerecha(activo);
            cambiarTexto();
        }
    }//GEN-LAST:event_btnSiActionPerformed

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
        // TODO add your handling code here:
        if(activo.getHijoIzquierdo().getHijoIzquierdo()==null && activo.getHijoIzquierdo().getHijoDerecho()==null){
            //mandar a la ventana de adivinado el personaje
        }else{
            activo = activo.avanzarIzquierda(activo);
            cambiarTexto();
        }
    }
    
    public void cambiarTexto(){
        if(activo!=null){
            lblPregunta.setText("Es: "+activo.getTexto());
        }
        
    }//GEN-LAST:event_btnNoActionPerformed

    private void SetImageLabel(JLabel labelName, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon (
                image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT)
        );
        labelName.setIcon(icon);
        this.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImgAki;
    private javax.swing.JButton btnNo;
    private javax.swing.JButton btnSi;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblPregunta;
    // End of variables declaration//GEN-END:variables
}
